AdobeDocs/experience-platform-apis

gatsby-config.js, src/pages/api/1.4.md, src/pages/api/access-control.md, src/pages/api/audit-query.md, src/pages/api/catalog.md, src/pages/api/data-access.md, src/pages/api/data-ingestion.md, src/pages/api/data-prep.md, src/pages/api/dataset-service.md, src/pages/api/flow-service.md, src/pages/api/identity-service.md, src/pages/api/index.md, src/pages/api/observability-insights.md, src/pages/api/policy-service.md, src/pages/api/privacy-service.md, src/pages/api/profile.md, src/pages/api/query-service.md, src/pages/api/reactor.md, src/pages/api/sandbox.md, src/pages/api/schema-registry.md, src/pages/api/segmentation.md, src/pages/api/sensei-machine-learning.md, src/pages/index.md
https://jira.corp.adobe.com/browse/PLAT-95292
=> PLAT-95292 - Draft initial site [READY]

src/swagger-specs/audit-query.yaml
https://jira.corp.adobe.com/browse/PLAT-105287
=> PLAT-105287 - Update filtering info, operationIds, and summaries [READY]

src/pages/index.md
=> Bug Fix: Fix typo in line 106 [READY]

src/swagger-specs/schema-registry.yaml
https://jira.corp.adobe.com/browse/PLAT-106094
=> PLAT-106094 - Update descriptions for start and limit in XDM swagger [READY]

src/swagger-specs/audit-query.yaml
=> PLAT-104928 - Style updates for Audit Query swagger [READY]

src/swagger-specs/dataset-service.yaml
=> PLAT-105928 - Style improvements to Dataset Service swagger [READY]

src/swagger-specs/observability-insights.yaml
=> PLAT-105928 - Style updates for Observability Insights swagger [READY]

src/swagger-specs/schema-registry.yaml
=> PLAT-105928 - Style/content updates for Schema Registry [READY]

src/swagger-specs/reactor.yaml
=> PLAT-105928 - Reactor API content updates [READY]

src/swagger-specs/schema-registry.yaml
https://jira.corp.adobe.com/browse/PLATIR-17633
=> PLAT-105928 - Update descriptions for Accept header params to be easier to understand [READY]

src/swagger-specs/audit-query.yaml
=> PLAT-105928 - Updates re: pagination in Audit Query API [READY]

src/swagger-specs/observability-insights.yaml, src/swagger-specs/privacy-service.yaml, src/swagger-specs/reactor.yaml
=> PLAT-105928 - Add pagination info for Observability, Privacy, and Reactor [READY]

src/swagger-specs/dataset-service.yaml, src/swagger-specs/observability-insights.yaml, src/swagger-specs/policy-service.yaml, src/swagger-specs/privacy-service.yaml, src/swagger-specs/profile.yaml, src/swagger-specs/reactor.yaml, src/swagger-specs/schema-registry.yaml
=> PLAT-105928 - Add ExL links to endpoints in several swaggers [READY]

src/swagger-specs/audit-query.yaml
=> PLAT-117241/API-Audit-Documentation-Changes-for-GA [REVIEW]

src/swagger-specs/audit-query.yaml
=> PLAT-120108/Remove-beta-tag-from-Audit-Query-API-swagger

src/swagger-specs/observability-insights.yaml
=> PLAT-121945/Observaility-outdated-postman-link [COMPLETED]

src/swagger-specs/destination-authoring.yaml
Various parameter updates for https://jira.corp.adobe.com/browse/PLAT-120164 and https://jira.corp.adobe.com/browse/PLAT-120461
=> Updates for PLAT-120164 and PLAT-120461

src/pages/references/destination-authoring.md
still testing for https://jira.corp.adobe.com/browse/PLAT-128760
see previous PRs for motivation
=> Removing another file to try and hide destination SDK from TOC

src/pages/references/destinations.md, src/swagger-specs/destinations.yaml
Testing for https://jira.corp.adobe.com/browse/PLAT-128760 - looking to see if I can publish an API reference without it being displayed in a dropdown selector
=> Testing for PLAT-128760 - destinations openapi reference

gatsby-config.js
=> Adding gatsby config for Destinations API

src/swagger-specs/destination-authoring.yaml
=> More testing to see if my updates are reflected on the devsite

src/pages/index.md
=> Adding destinations API to index.md

src/swagger-specs/destinations.yaml
=> Some more updates to destinations.yaml

gatsby-config.js, src/pages/references/destinations.md, src/swagger-specs/destinations.yaml
Some more testing for [PLAT-128760](https://jira.corp.adobe.com/browse/PLAT-128760)
=> Testing destinations.yaml again

gatsby-config.js, src/pages/index.md, src/pages/references/destinations.md, src/swagger-specs/destinations.yaml
Testing the publishing workflow for https://jira.corp.adobe.com/browse/PLAT-128760
=> Testing the publishing workflow by publishing new Destinations API reference

src/swagger-specs/destinations-copy.yaml
still testing for https://jira.corp.adobe.com/browse/PLAT-128760
=> Uploading one more APi spec to test if we can publish without adding to dropdown list

src/pages/references/destinations-copy.md
=> Adding destinations-copy.md reference file

src/swagger-specs/destinations.yaml
Updates for https://jira.corp.adobe.com/browse/PLAT-128760
=> PLAT-128760: Several updates as per latest additions to internal OpenAPI file

src/swagger-specs/destinations.yaml
Continuing with updates for https://jira.corp.adobe.com/browse/PLAT-128760
=> Destinations API: Syncing latest updates from internal OpenAPI reference

src/swagger-specs/destinations.yaml
continuing the work for https://jira.corp.adobe.com/browse/PLAT-128760
=> Several more updates. Wordsmithing.

src/swagger-specs/destinations.yaml
Continuing with the updates for https://jira.corp.adobe.com/browse/PLAT-128760
=> Several more updates for PLAT-128760

src/swagger-specs/destinations.yaml
Further updates for PLAT-128760
=> Syncing up external API reference with internal one

src/swagger-specs/destinations.yaml
* exhaustive param descriptions 
* correct headers
* several other verbiage updates to improve definitions and descriptions
=> PLAT:128760: Several updates, description below

src/swagger-specs/reactor.yaml
https://jira.corp.adobe.com/browse/PLAT-129045
=> PLAT-129045 - Add skip_symlinks attribute for hosts in Reactor API [READY]

src/swagger-specs/segmentation.yaml
This PR is to update the Swagger with the updates for the following features:
- 4000 segments supported: https://jira.corp.adobe.com/browse/CORE-78742
- The new Audiences endpoint: https://jira.corp.adobe.com/browse/CORE-78521
=> Segmentation Swagger updates

src/swagger-specs/segmentation.yaml
This PR adds descriptions to the fields within the Audiences endpoint.
=> Adding descriptions to the Audiences stuff

src/@adobe/gatsby-theme-aio/components/OpenAPIBlock/index.js
Fix for the styling issue shown below.
https://user-images.githubusercontent.com/19704189/182937438-37d09d9b-f619-422e-919c-4a8f2c3e3069.mp4
At first, we are fixing this on the Experience Platform repository level until a PR fix to the theme is merged upstream by the devsite team. At that point, we will remove the OpenAPIBlock from the Experience Platform repository.
=> Fix for visual bug in dropdown arrow for OpenAPI 3.0 examples

src/@adobe/gatsby-theme-aio/components/OpenAPIBlock/index.js
updating an absolute link which was incorrect in PR #119
=> Followup to PR #119 - one more fix attempt

gatsby-config.js, src/pages/index.md, src/swagger-specs/destinations.yaml, src/swagger-specs/flow-service.yaml
Publishing the destinations-focused Flow Service API docs. At first, this has specific and complete information for connecting to Amazon S3 and SFTP destinations. We will be adding more destination schemas and examples to the reference in the coming weeks/months.
=> Updates to publish the Destinations API [REVIEW]

src/swagger-specs/flow-service.yaml
=> BUGFIX - Link and description correction in Flow Service - sources doc [READY]

src/swagger-specs/query-service.yaml
=> ens32110 Hide alert subscriptions

src/swagger-specs/query-service.yaml
=> ens32110 removed alert subscriptions API title

package.json, yarn.lock
=> Updating the version to .6

src/swagger-specs/catalog.yaml
https://jira.corp.adobe.com/browse/PLAT-132840
Also updating the Catalog Swagger to v3 and adding a new parameter:
https://jira.corp.adobe.com/browse/PLAT-136738
=> Include two API calls from the documentation in the Catalog Swagger and Postman collection - READY

src/swagger-specs/sandbox.yaml
=> PLAT-126504/Document-enhancements-to-the-Sandbox-API-Reference [REVIEW]

src/swagger-specs/query-service.yaml
https://jira.corp.adobe.com/browse/PLAT-136032
No details available as yet.
=> PLAT-136032 update swagger doc with /accelerated-queries [READY]

src/swagger-specs/destination-authoring.yaml
Updated the definitions for the parameters `acceptsCustomNamespaces`, `acceptsAttributes`, `acceptedGlobalNamespaces` based on explanations from meeting with engineering. Also, made some other small updates to resolve minor validation issues.
=> BUGFIX: Definition updates and other improvements [REVIEW]

src/swagger-specs/query-service.yaml
Overhaul of descriptions, styling and examples used in QS PAI docs. Ensuring accurate and up to date information for public facing swaggers.
https://jira.corp.adobe.com/browse/PLAT-107430
=> PLAT-107430 NEW QS style & content updates[READY]

src/swagger-specs/schema-registry.yaml
https://jira.corp.adobe.com/browse/PLAT-127243
=> PLAT-127243  - Update description/example for data type creation [READY]

src/swagger-specs/access-control.yaml
Updated to include descriptions for Permissions
=> PLAT-140505/Missing-descriptions-in-Access-Control-swagger

src/swagger-specs/access-control.yaml
Updates to include descriptions
=> Updates made to include descriptions

src/swagger-specs/access-control.yaml
=> PLAT-140505/Missing-descriptions-in-Access-Control

yarn.lock
Re-compiling yarn.lock with update to the theme.
=> Recompiling yarn.lock file

src/swagger-specs/data-access.yaml
Tracking work here: https://jira.corp.adobe.com/browse/PLAT-139851
=> PLAT-139851 - Style/content enhancements for Data Access swagger - READY

src/swagger-specs/catalog.yaml
=> PLAT-105930/Swagger-enhancements-Catalog-API

src/swagger-specs/access-control.yaml
=> PLAT-145059/Access-control-update-ACS-API-doc-to-specify-the-required-role-with-the-org

src/swagger-specs/schema-registry.yaml
=> ens32110-bugfix Corrected broken link

src/pages/index.md
Fix for broken links. 
replacing Data Ingestion link with two new pages;
batch ingestion and streaming ingestion.
https://jira.corp.adobe.com/browse/PLAT-139820
=> updates to index.md. Fix for broken links[READY]

src/swagger-specs/segmentation.yaml
Updating Swagger with details on segment definitions
=> Swagger update

src/swagger-specs/destinations.yaml
https://jira.corp.adobe.com/browse/PLAT-146996
https://jira.corp.adobe.com/browse/PLAT-136263
More information coming soon.
=> PLAT-146996: Significant updates to destinations yaml for new cloud storage export capabilities [REVIEW]

src/swagger-specs/segmentation.yaml
https://jira.corp.adobe.com/browse/PLAT-164744?filter=-1
=> PLAT-164744 - API Request Documentation change - API triggers when Mandatory Attribute does not exist - READY

src/swagger-specs/privacy-service.yaml
https://jira.corp.adobe.com/browse/PLAT-164976
=> PLAT 164976 Privacy Service support for Utah privacy act[READY]

src/swagger-specs/destinations.yaml
Updates for PLAT-169551 and PLAT-172040
=> PLAT-169551: Updating connection spec IDs for batch destinations and other related updates after cloud storage destinations GA [REVIEW]

src/swagger-specs/access-control.yaml, src/swagger-specs/audit-query.yaml, src/swagger-specs/data-prep.yaml, src/swagger-specs/dataset-service.yaml, src/swagger-specs/flow-service.yaml, src/swagger-specs/observability-insights.yaml, src/swagger-specs/policy-service.yaml, src/swagger-specs/query-service.yaml, src/swagger-specs/sandbox.yaml, src/swagger-specs/sensei-machine-learning.yaml
Bump versioning for Swaggers (that don't have errors) to Open API 3.0.
=> Versioning

src/swagger-specs/catalog.yaml
Removed the /tags endpoint. Remove connection, connectionId and /connections references,
Remove connector, connectorId and /connectors references
Remove statsCache, state, namespace, schemaMetadata, fileDescription.persisted, requestStartDate, and fields field references
https://jira.corp.adobe.com/browse/PLAT-153161
Deprecation of various fields and endpoints ion the Catalog Service API
using redocly
=> PLAT-153161 Update Catalog's public documentation[READY]

src/swagger-specs/catalog.yaml
Info provided in wiki:
https://wiki.corp.adobe.com/display/DMARomania/%5BCatalog+-+September+2023%5D+Changes+for+public+documentation 
https://jira.corp.adobe.com/browse/PLAT-168704 
Deprecated info
=> PLAT-168704 Catalog Update deprecated information from public documentation[READY]

src/swagger-specs/access-control.yaml
=> PLAT-168652/Attribute-based-access-control-documentation-review

src/pages/references/access-control.md
This is to test the redocly updates.
Making a staging branch as well so we don't pollute main with this.
=> Trying a redocly

src/pages/references/access-control.md
=> More tests

.github/workflows/deploy.yml
=> Adding missing deploy key

src/swagger-specs/streaming-ingestion.yml
Updated API to include required label for flowId
https://jira.corp.adobe.com/browse/PLAT-183254
=> PLAT-183254/Add-FlowID-To-Required-Section

src/pages/references/access-control.md
Adding layout none to see if it makes it look better wide.
=> Trying this to see if it helps

src/pages/references/audit-query.md, src/pages/references/batch-ingestion.md, src/pages/references/catalog.md, src/pages/references/data-access.md, src/pages/references/data-prep.md, src/pages/references/dataset-service.md, src/pages/references/destination-authoring.md, src/pages/references/destinations.md, src/pages/references/flow-service.md, src/pages/references/identity-service.md, src/pages/references/observability-insights.md, src/pages/references/policy-service.md, src/pages/references/privacy-service.md, src/pages/references/profile.md, src/pages/references/query-service.md, src/pages/references/reactor.md, src/pages/references/sandbox.md, src/pages/references/schema-registry.md, src/pages/references/segmentation.md, src/pages/references/sensei-machine-learning.md, src/pages/references/streaming-ingestion.md
Changing the others to redoclys.
=> Updating the other ones to redoclys as well

src/swagger-specs/schema-registry.yaml
Trying to fix the Schema Registry Swagger to not break.
=> Trying to fix the errors

src/swagger-specs/schema-registry.yaml
=> More fixes?

src/swagger-specs/schema-registry.yaml
=> One more fix?

src/swagger-specs/privacy-service.yaml, src/swagger-specs/profile.yaml, src/swagger-specs/query-service.yaml, src/swagger-specs/reactor.yaml, src/swagger-specs/sandbox.yaml, src/swagger-specs/schema-registry.yaml, src/swagger-specs/segmentation.yaml, src/swagger-specs/sensei-machine-learning.yaml, src/swagger-specs/streaming-ingestion.yml
Adding x-summary tags to half of the Swaggers.
=> Add x-summary tags

src/swagger-specs/audit-query.yaml, src/swagger-specs/data-prep.yaml, src/swagger-specs/dataset-service.yaml, src/swagger-specs/destination-authoring.yaml, src/swagger-specs/destinations.yaml, src/swagger-specs/flow-service.yaml, src/swagger-specs/identity-service.yaml, src/swagger-specs/policy-service.yaml
[PLAT-191496](https://jira.corp.adobe.com/browse/PLAT-191496)
Fix for width issue reported in https://jira.corp.adobe.com/browse/DEVSITE-1010
=> PLAT-191496: Updates to add x-summary params to 1st half of API references [READY]

src/pages/references/access-control.md, src/pages/references/audit-query.md, src/pages/references/batch-ingestion.md, src/pages/references/catalog.md, src/pages/references/data-access.md, src/pages/references/data-prep.md, src/pages/references/dataset-service.md, src/pages/references/destination-authoring.md, src/pages/references/destinations.md, src/pages/references/flow-service.md, src/pages/references/identity-service.md, src/pages/references/observability-insights.md, src/pages/references/policy-service.md, src/pages/references/privacy-service.md, src/pages/references/profile.md, src/pages/references/query-service.md, src/pages/references/reactor.md, src/pages/references/sandbox.md, src/pages/references/schema-registry.md, src/pages/references/segmentation.md, src/pages/references/sensei-machine-learning.md, src/pages/references/streaming-ingestion.md
=> One more fix check

src/pages/references/access-control.md, src/pages/references/audit-query.md, src/pages/references/batch-ingestion.md, src/pages/references/catalog.md, src/pages/references/data-access.md, src/pages/references/data-prep.md, src/pages/references/dataset-service.md, src/pages/references/destination-authoring.md, src/pages/references/destinations.md, src/pages/references/flow-service.md, src/pages/references/identity-service.md, src/pages/references/observability-insights.md, src/pages/references/policy-service.md, src/pages/references/privacy-service.md, src/pages/references/profile.md, src/pages/references/query-service.md, src/pages/references/reactor.md, src/pages/references/sandbox.md, src/pages/references/schema-registry.md, src/pages/references/segmentation.md, src/pages/references/sensei-machine-learning.md, src/pages/references/streaming-ingestion.md
=> More fixes

src/pages/references/access-control.md, src/pages/references/audit-query.md, src/pages/references/batch-ingestion.md, src/pages/references/catalog.md, src/pages/references/data-access.md, src/pages/references/data-prep.md, src/pages/references/dataset-service.md, src/pages/references/destination-authoring.md, src/pages/references/destinations.md, src/pages/references/flow-service.md, src/pages/references/identity-service.md, src/pages/references/observability-insights.md, src/pages/references/policy-service.md, src/pages/references/privacy-service.md, src/pages/references/profile.md, src/pages/references/query-service.md, src/pages/references/reactor.md, src/pages/references/sandbox.md, src/pages/references/schema-registry.md, src/pages/references/segmentation.md, src/pages/references/sensei-machine-learning.md, src/pages/references/streaming-ingestion.md
=> One more test

src/pages/references/access-control.md, src/pages/references/audit-query.md, src/pages/references/batch-ingestion.md, src/pages/references/catalog.md, src/pages/references/data-access.md, src/pages/references/data-prep.md, src/pages/references/dataset-service.md, src/pages/references/destination-authoring.md, src/pages/references/destinations.md, src/pages/references/flow-service.md, src/pages/references/identity-service.md, src/pages/references/observability-insights.md, src/pages/references/policy-service.md, src/pages/references/privacy-service.md, src/pages/references/profile.md, src/pages/references/query-service.md, src/pages/references/reactor.md, src/pages/references/sandbox.md, src/pages/references/schema-registry.md, src/pages/references/segmentation.md, src/pages/references/sensei-machine-learning.md, src/pages/references/streaming-ingestion.md
=> More updates

src/pages/index.md, static/swagger-specs/access-control.yaml, static/swagger-specs/audit-query.yaml, static/swagger-specs/batch-ingestion.yaml, static/swagger-specs/data-access.yaml, static/swagger-specs/data-prep.yaml, static/swagger-specs/dataset-service.yaml, static/swagger-specs/destination-authoring.yaml, static/swagger-specs/destinations.yaml, static/swagger-specs/flow-service.yaml, static/swagger-specs/identity-service.yaml, static/swagger-specs/observability-insights.yaml, static/swagger-specs/policy-service.yaml, static/swagger-specs/privacy-service.yaml, static/swagger-specs/profile.yaml, static/swagger-specs/query-service.yaml, static/swagger-specs/reactor.yaml, static/swagger-specs/sandbox.yaml
Updating the index.md overview page and every API reference yaml page with a section to call out the new interactive API functionality
=> Interactive API improvements [REVIEW]

static/swagger-specs/reactor.yaml
=> PDCL-12095/Document-the-extension-package-usage-authorization-endpoints

static/swagger-specs/reactor.yaml
=> PDCL-12095/Document-the-extension-package-usage-authorization-endpoints-issue-resolved

static/swagger-specs/reactor.yaml
=> PDCL-12095/Document-the-extension-package-usage-authorization-endpoints-updates

static/policy-service.json, static/privacy-service.json, static/swagger-specs/policy-service.yaml, static/swagger-specs/privacy-service.yaml
https://jira.corp.adobe.com/browse/PLAT-195313 
https://jira.corp.adobe.com/browse/PLATIR-28194 
Remove the analyticsDeleteMethod from the API documentation.
and
The url mentioned in the Policy Service API is incorrect. updating it.
=> ens32110 bugfix PLATIR-28194 PLAT-195313 [READY]

static/swagger-specs/data-access.yaml
fixed duplicate description typo
=> ens32110 bugfix Update data-access.yaml

gatsby-config.js, src/pages/references/unified-tags.md, static/swagger-specs/unified-tags.yaml
Adding the Unified Folders + Tags to our OpenAPI docs.
=> Unified Folders + Unified Tags APIs

static/swagger-specs/unified-tags.yaml
Adding a few more sample descriptions.
=> Folders text

static/swagger-specs/data-hygiene.yaml
Remove TTL history features from documentation of Dataset Expiration
https://jira.corp.adobe.com/browse/PLAT-168591
=> PLAT-168591 Remove TTL history features from documentation of Dataset Expiration[REVIEW]

static/swagger-specs/data-access.yaml, static/swagger-specs/data-hygiene.yaml
https://jira.corp.adobe.com/browse/PLAT-183484 
Add Deprecation notice in Data Access API
=> PLAT-183484 Add Deprecation notice in Data Access API [READY]

gatsby-config.js, src/pages/references/mtls.md, static/swagger-specs/data-hygiene.yaml, static/swagger-specs/mtls.yaml, static/swagger-specs/policy-service.yaml
https://jira.corp.adobe.com/browse/PLAT-193044 
The new MTLS service endpoint for customers
=> PLAT-193044 Provide a Doc for mTLS API (to retrieve public cert)[REVIEW]

src/pages/index.md
=> ens32110 bugfix add mtls API page to index[READY]

gatsby-config.js, package.json
Removing unneeded dependencies.
=> Remove stuff

static/swagger-specs/segmentation.yaml
https://jira.corp.adobe.com/browse/CORE-110053
=> CORE-110053 - Removing ttlInDays

src/pages/credentials/GetCredentialOAuth2.js
Add product name to the block.
=> Add product name

static/swagger-specs/sandbox.yaml
=> PLAT-199452/GitHub-issue-3368-remove-x-sandbox-name-from-list-of-required-headers-for-list-and-lookup

src/pages/references/access-control.md, src/pages/references/audit-query.md, src/pages/references/batch-ingestion.md, src/pages/references/catalog.md, src/pages/references/data-access.md, src/pages/references/data-prep.md, src/pages/references/dataset-service.md, src/pages/references/destination-authoring.md, src/pages/references/destinations.md, src/pages/references/flow-service.md, src/pages/references/identity-service.md, src/pages/references/observability-insights.md, src/pages/references/policy-service.md, src/pages/references/privacy-service.md, src/pages/references/profile.md, src/pages/references/query-service.md, src/pages/references/reactor.md, src/pages/references/sandbox.md, src/pages/references/schema-registry.md, src/pages/references/segmentation.md, src/pages/references/sensei-machine-learning.md, src/pages/references/streaming-ingestion.md, src/pages/references/unified-tags.md, static/swagger-specs/profile.yaml, static/swagger-specs/segmentation.yaml
Updates for a big pile of tickets:
https://jira.corp.adobe.com/browse/PLAT-203267
https://jira.corp.adobe.com/browse/PLAT-203177
https://jira.corp.adobe.com/browse/PLAT-203170
https://jira.corp.adobe.com/browse/PLAT-203175
https://jira.corp.adobe.com/browse/PLAT-203176
https://jira.corp.adobe.com/browse/PLAT-203173
https://jira.corp.adobe.com/browse/PLAT-203168
https://jira.corp.adobe.com/browse/PLAT-203171
=> API updates 

static/swagger-specs/profile.yaml, static/swagger-specs/segmentation.yaml
This is to resolve the issues with the "bulk get" request bodies not showing up.
=> More API fixes

src/pages/credentials/GetCredentialOAuth2.js
=> Another fix

static/swagger-specs/destinations.yaml
https://jira.corp.adobe.com/browse/PLAT-189876
Items for the September release, updating several options related to dataset export functionality
=> PLAT-189876: Dataset export enhancements to customize folder name, export mode, and scheduling [READY]

static/swagger-specs/access-control.yaml
Trying to add multiple pickers to the thingy
=> Testing a thing

static/swagger-specs/observability-insights.yaml
https://jira.corp.adobe.com/browse/PLAT-209639?filter=608795
=> PLAT-209639/update-observability-inights-api [REVIEW]

static/swagger-specs/observability-insights.yaml
just a teeny tiny fix for a duplicate backtick
=> removed duplicate backtick

src/pages/credentials/GetCredentialOAuth2.js
testing to see if i can unbold this text for a "hack" to add a description.
=> Unbolds your text

src/pages/credentials/GetCredentialOAuth2.js
Add description for the credential details part?
=> Add description

gatsby-browser.js, src/pages/credentials/GetCredentialOAuth2.js
Adding Analytics to the Get credentials stuff.
=> Adding Analytics - WIP

gatsby-browser.js
=> Analytics - WIP

static/swagger-specs/audit-query.yaml
Updated how adding additional filtering properties is formatted in the documentation. This is internally tracked via PLAT-212918.
=> Updated audit list event property filtering example

static/swagger-specs/observability-insights.yaml
Added in an additional optional header parameter to the metric request. Reference PLAT-213020 for tracking internally.
=> Updated observability API metric request header

src/pages/references/data-distiller-auth.md
=> PLAT-211857 Bugfix - typo correction in relative link

static/swagger-specs/unified-tags.yaml
clarify endpoints as unified tags and unified folders
Update endpoints
add unifiedtags and unifiedfolders to their respective endpoints
=> Update unified-tags.yaml endpoints

static/swagger-specs/unified-tags.yaml
https://jira.corp.adobe.com/browse/PLAT-213769
https://jira.corp.adobe.com/browse/PLAT-213769
=> Api updates

static/swagger-specs/segmentation.yaml
=> Add query parameter to API

static/swagger-specs/flow-service.yaml
Refer to: https://jira.corp.adobe.com/browse/PLAT-216123
=> PLAT-216123/update-sources-flow-service [REVIEW]

static/swagger-specs/flow-service.yaml
=> fixing merge conflict

static/swagger-specs/privacy-service.yaml
Added /jobs/JOB_ID/content endpoint for Privacy service API
https://jira.corp.adobe.com/browse/PLAT-219045 
Missing information
=> PLAT-219045 Add /content endpoint [READY]

static/swagger-specs/schema-registry.yaml
Added the new `@type` value to the "create a descriptor" call.
=> added new @type field

static/swagger-specs/profile.yaml
Adding deprecation notice for ExperienceEvents for entities.
=> Entities fix
